export const initialMovies = [
  {
    Title: "Guardians of the Galaxy Vol. 2",
    Year: "2017",
    Rated: "PG-13",
    Released: "05 May 2017",
    Runtime: "136 min",
    Genre: "Action, Adventure, Comedy",
    Director: "James Gunn",
    Writer: "James Gunn, Dan Abnett, Andy Lanning",
    Actors: "Chris Pratt, Zoe Saldana, Dave Bautista",
    Plot: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 15 wins & 59 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.6/10" },
      { Source: "Rotten Tomatoes", Value: "85%" },
      { Source: "Metacritic", Value: "67/100" },
    ],
    Metascore: "67",
    imdbRating: "7.6",
    imdbVotes: "674,085",
    imdbID: "tt3896198",
    Type: "movie",
    DVD: "22 Aug 2017",
    BoxOffice: "$389,813,101",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Harry Potter and the Deathly Hallows: Part 2",
    Year: "2011",
    Rated: "PG-13",
    Released: "15 Jul 2011",
    Runtime: "130 min",
    Genre: "Adventure, Fantasy, Mystery",
    Director: "David Yates",
    Writer: "Steve Kloves, J.K. Rowling",
    Actors: "Daniel Radcliffe, Emma Watson, Rupert Grint",
    Plot: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
    Language: "English, Latin",
    Country: "United Kingdom, United States",
    Awards: "Nominated for 3 Oscars. 46 wins & 94 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.1/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "85/100" },
    ],
    Metascore: "85",
    imdbRating: "8.1",
    imdbVotes: "865,376",
    imdbID: "tt1201607",
    Type: "movie",
    DVD: "11 Nov 2011",
    BoxOffice: "$381,447,587",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Godfather",
    Year: "1972",
    Rated: "R",
    Released: "24 Mar 1972",
    Runtime: "175 min",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Writer: "Mario Puzo, Francis Ford Coppola",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    Language: "English, Italian, Latin",
    Country: "United States",
    Awards: "Won 3 Oscars. 31 wins & 30 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.2/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "100/100" },
    ],
    Metascore: "100",
    imdbRating: "9.2",
    imdbVotes: "1,833,171",
    imdbID: "tt0068646",
    Type: "movie",
    DVD: "11 May 2004",
    BoxOffice: "$136,381,073",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Transformers",
    Year: "2007",
    Rated: "PG-13",
    Released: "03 Jul 2007",
    Runtime: "144 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Michael Bay",
    Writer: "Roberto Orci, Alex Kurtzman, John Rogers",
    Actors: "Shia LaBeouf, Megan Fox, Josh Duhamel",
    Plot: "An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 25 wins & 50 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDg1NTU2OWEtM2UzYi00ZWRmLWEwMTktZWNjYWQ1NWM1OThjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.0/10" },
      { Source: "Rotten Tomatoes", Value: "58%" },
      { Source: "Metacritic", Value: "61/100" },
    ],
    Metascore: "61",
    imdbRating: "7.0",
    imdbVotes: "636,198",
    imdbID: "tt0418279",
    Type: "movie",
    DVD: "16 Oct 2007",
    BoxOffice: "$319,246,193",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avengers: Endgame",
    Year: "2019",
    Rated: "PG-13",
    Released: "26 Apr 2019",
    Runtime: "181 min",
    Genre: "Action, Adventure, Drama",
    Director: "Anthony Russo, Joe Russo",
    Writer: "Christopher Markus, Stephen McFeely, Stan Lee",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    Plot: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    Language: "English, Japanese, Xhosa, German",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 70 wins & 132 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "78/100" },
    ],
    Metascore: "78",
    imdbRating: "8.4",
    imdbVotes: "1,103,672",
    imdbID: "tt4154796",
    Type: "movie",
    DVD: "30 Jul 2019",
    BoxOffice: "$858,373,000",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
